package com.nf147.dao;

import com.nf147.entity.PsApiresponse;
import java.util.List;

public interface PsApiresponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_apiresponse
     *
     * @mbg.generated
     */
    int insert(PsApiresponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_apiresponse
     *
     * @mbg.generated
     */
    List<PsApiresponse> selectAll();
}