package com.nf147.dao;

import com.nf147.entity.PsCategory;
import java.util.List;

public interface PsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_category
     *
     * @mbg.generated
     */
    int insert(PsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_category
     *
     * @mbg.generated
     */
    PsCategory selectByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_category
     *
     * @mbg.generated
     */
    List<PsCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PsCategory record);
}