package com.nf147.dao;

import com.nf147.entity.PsOrder;
import java.util.List;

public interface PsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_order
     *
     * @mbg.generated
     */
    int insert(PsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_order
     *
     * @mbg.generated
     */
    PsOrder selectByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_order
     *
     * @mbg.generated
     */
    List<PsOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PsOrder record);
}