package com.nf147.dao;

import com.nf147.entity.PsTag;
import java.util.List;

public interface PsTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_tag
     *
     * @mbg.generated
     */
    int insert(PsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_tag
     *
     * @mbg.generated
     */
    PsTag selectByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_tag
     *
     * @mbg.generated
     */
    List<PsTag> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PsTag record);
}