package com.nf147.dao;

import com.nf147.entity.PsUser;
import java.util.List;

public interface PsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_user
     *
     * @mbg.generated
     */
    int insert(PsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_user
     *
     * @mbg.generated
     */
    PsUser selectByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_user
     *
     * @mbg.generated
     */
    List<PsUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PsUser record);
}