package com.nf147.entity;

import java.util.Date;

public class PsOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_order.o_id
     *
     * @mbg.generated
     */
    private Integer oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_order.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_order.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_order.shipDate
     *
     * @mbg.generated
     */
    private Date shipdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_order.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_order.complete
     *
     * @mbg.generated
     */
    private String complete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_order.o_id
     *
     * @return the value of ps_order.o_id
     *
     * @mbg.generated
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_order.o_id
     *
     * @param oId the value for ps_order.o_id
     *
     * @mbg.generated
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_order.p_id
     *
     * @return the value of ps_order.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_order.p_id
     *
     * @param pId the value for ps_order.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_order.quantity
     *
     * @return the value of ps_order.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_order.quantity
     *
     * @param quantity the value for ps_order.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_order.shipDate
     *
     * @return the value of ps_order.shipDate
     *
     * @mbg.generated
     */
    public Date getShipdate() {
        return shipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_order.shipDate
     *
     * @param shipdate the value for ps_order.shipDate
     *
     * @mbg.generated
     */
    public void setShipdate(Date shipdate) {
        this.shipdate = shipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_order.status
     *
     * @return the value of ps_order.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_order.status
     *
     * @param status the value for ps_order.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_order.complete
     *
     * @return the value of ps_order.complete
     *
     * @mbg.generated
     */
    public String getComplete() {
        return complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_order.complete
     *
     * @param complete the value for ps_order.complete
     *
     * @mbg.generated
     */
    public void setComplete(String complete) {
        this.complete = complete == null ? null : complete.trim();
    }
}