package com.nf147.entity;

public class PsUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user.u_id
     *
     * @mbg.generated
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user.u_name
     *
     * @mbg.generated
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user.firstName
     *
     * @mbg.generated
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user.lastName
     *
     * @mbg.generated
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user.u_status
     *
     * @mbg.generated
     */
    private Integer uStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user.u_id
     *
     * @return the value of ps_user.u_id
     *
     * @mbg.generated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user.u_id
     *
     * @param uId the value for ps_user.u_id
     *
     * @mbg.generated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user.u_name
     *
     * @return the value of ps_user.u_name
     *
     * @mbg.generated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user.u_name
     *
     * @param uName the value for ps_user.u_name
     *
     * @mbg.generated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user.firstName
     *
     * @return the value of ps_user.firstName
     *
     * @mbg.generated
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user.firstName
     *
     * @param firstname the value for ps_user.firstName
     *
     * @mbg.generated
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user.lastName
     *
     * @return the value of ps_user.lastName
     *
     * @mbg.generated
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user.lastName
     *
     * @param lastname the value for ps_user.lastName
     *
     * @mbg.generated
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user.email
     *
     * @return the value of ps_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user.email
     *
     * @param email the value for ps_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user.password
     *
     * @return the value of ps_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user.password
     *
     * @param password the value for ps_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user.u_status
     *
     * @return the value of ps_user.u_status
     *
     * @mbg.generated
     */
    public Integer getuStatus() {
        return uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user.u_status
     *
     * @param uStatus the value for ps_user.u_status
     *
     * @mbg.generated
     */
    public void setuStatus(Integer uStatus) {
        this.uStatus = uStatus;
    }
}